In [1]:
import cv2
from skimage import io
from PIL import Image  
import numpy as np
import os,sys
#from cv2 import cv

In [2]:
instance_masks = []
class_ids = []

In [4]:
image = cv2.imread("2121.png")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#gray=cv2.GaussianBlur(gray, (3, 3), 0)  
#gray=cv2.Canny(gray,100,300)  

In [5]:
img3=np.array(gray)
[x,y]=img3.shape
print([x,y])
a = np.zeros([x,y,3])
b = a[:,:,1]
print(a.shape)
print(a)
print(b.shape)


[10, 10]
(10, 10, 3)
[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0. 

In [6]:
print(gray)
#print(image.shapes())

[[ 76  76  76  76  76  76  76  76  76  76]
 [ 76  76  76  76  76  76  76  76  76  76]
 [ 76  76  76  76  76  76  76  76  76  76]
 [ 76  76  76  76  76  76  76  76  76  76]
 [ 76  76  76  76  76  76  76  76  76  76]
 [150 150 150 150 150 150 150 150 150 150]
 [150 150 150 150 150 150 150 150 150 150]
 [150 150 150 150 150 150 150 150 150 150]
 [150 150 150 150 150 150 150 150 150 150]
 [150 150 150 150 150 150 150 150 150 150]]


In [7]:
ret, binary = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)

In [8]:
print(binary)
print(ret)
#print(binary.shapes())

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255]]
100.0


In [9]:
binary,contours,hierarchy= cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_NONE)
print(binary.shape)

(10, 10)


In [ ]:
# 将图像的区域分别画出来
for i in range(len(contours)):
    newMask= np.zeros([x,y,3])
    cv2.drawContours(newMask, contours, i, (255, 255, 255), -1)
    newMask = newMask[:,:,1]
    cv2.HoughLinesP
    cv2.namedWindow(""+str(i)+"",i);
    cv2.resizeWindow("enhanced", 640, 480);
    cv2.imshow(""+str(i)+"", newMask)
#cv2.imwrite("44.png", image)
cv2.waitKey(0)

In [28]:
for i in range(len(contours)):
    newMask= np.zeros([x,y,3])
    #print(newMask)
    cv2.drawContours(newMask, contours, i, (1, 1, 1), -1)
    #newMask = cv2.cvtColor(newMask, cv2.COLOR_BGR2GRAY)
    newMask = np.array(newMask[:,:,1], dtype=np.uint8)
    instance_masks.append(newMask)
    print(instance_masks)

[array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0

In [9]:
print(binary)
#print(binary.shapes)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [10]:
print(contours)
print(len(contours))

[array([[[556, 843]],

       [[556, 844]],

       [[556, 845]],

       ..., 
       [[559, 843]],

       [[558, 843]],

       [[557, 843]]], dtype=int32), array([[[167, 789]],

       [[167, 790]],

       [[167, 791]],

       ..., 
       [[170, 789]],

       [[169, 789]],

       [[168, 789]]], dtype=int32), array([[[233, 318]],

       [[233, 319]],

       [[233, 320]],

       ..., 
       [[236, 318]],

       [[235, 318]],

       [[234, 318]]], dtype=int32)]
3


In [11]:
print(hierarchy)

[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]


In [12]:
c = sorted(contours, key=cv2.contourArea, reverse=True)[0]

In [13]:
print(c)

[[[233 318]]

 [[233 319]]

 [[233 320]]

 ..., 
 [[236 318]]

 [[235 318]]

 [[234 318]]]


In [14]:
rect = cv2.minAreaRect(c)  
box = np.int0(cv2.boxPoints(rect))
#（x,y）为矩形左上角的坐标，（w,h）是矩形的宽和高
# x,y,w,h=cv2.boundingRect(cnt)

In [15]:
cv2.drawContours(a, contours, 1, (0, 255, 0), -1)
print(a)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [ ]:
# draw a bounding box arounded the detected barcode and display the image
#这几行代码可以保证图像大小可以通过鼠标拖动，实行缩放

cv2.HoughLinesP

cv2.namedWindow("Image",0);
cv2.resizeWindow("enhanced", 640, 480);

#cv2.drawContours(image, [box], 1, (0, 255, 0), -1)
cv2.imshow("Image", a)
#cv2.imwrite("44.png", image)
cv2.waitKey(0)

In [ ]:
Xs = [i[0] for i in box]
Ys = [i[1] for i in box]
x1 = min(Xs)
x2 = max(Xs)
y1 = min(Ys)
y2 = max(Ys)
hight = y2 - y1
width = x2 - x1
cropImg = image[y1:y1+hight, x1:x1+width]