# 用来将JPEG图像转化成PNG图像，将一定范围的像素值改成一个值

In [ ]:
from skimage import io
from PIL import Image  
import numpy as np
import os,sys
import datetime

In [2]:
file = open('filelist.txt')
lines = file.readlines()
aa=[]
for line in lines:
    #temp = line.replace('"','').split(',')
    aa.append(line)
print(aa) 

['10_left.jpg\n', '15_right.jpg\n', '17_right.jpg\n']


In [36]:
with open('filelist.txt', 'r') as f:
    trainList=[l.strip('\n') for l in f.readlines()]
print(trainList)

['10_left.jpg', '15_right.jpg', '17_right.jpg']


In [38]:
with open('filelistmask40.txt', 'r') as f:
    trainList1=[l.strip('\n') for l in f.readlines()]
print(trainList1)

['525_left.jpg', '179_left.jpg', '2804_left.jpg', '10_left.jpg', '17_right.jpg', '239_right.jpg', '525_right.jpg', '149_right.jpg', '47_right.jpg', '33_left.jpg', '465_right.jpg', '30_right.jpg', '761_left.jpg', '905_left.jpg', '239_left.jpg', '40_right.jpg', '1350_right.jpg', '1663_right.jpg', '687_left.jpeg', '696_right.jpg', '326_left.jpg', '211_left.jpg', '210_left.jpg', '47_left.jpg', '348_right.jpg', '30_left.jpg', '15_right.jpg', '326_right.jpg', '211_right.jpg', '1941_left.jpg', '178_right.jpg', '51_left.jpg', '229_right.jpg', '752_right.jpg', '460_right.jpg', '607_left.jpg', '460_left.jpg', '338_left.jpg', '231_left.jpg', '2496_right.jpg', '3563_left.jpg', '3422_left.jpg', '435_left.jpg', '179_right.jpg', '40_left.jpg', '36_left.jpg']


In [33]:
 for i in range(len(trainList)):
    print(trainList[i])

3422_left.jpg
1350_right.jpg
1663_right.jpg
2496_right.jpg


In [12]:
def ModifyRGBValue1(filelist):
    for num in range(len(filelist)):
        img=Image.open('test/'+filelist[num])
        #img=Image.open('test/1.jpg')
        arrimg = np.array(img)
        [x,y,z] = arrimg.shape
        R=arrimg[:,:,0]    #red
        G=arrimg[:,:,1]    #green
        B=arrimg[:,:,2];   #blue
        for i in range(x):
            for j in range(y):
                if( (arrimg[i,j,0] >= 225) and (arrimg[i,j,0] <=255) ):
                    arrimg[i,j,0] = 255
                else:
                    arrimg[i,j,0] = 0
                if( (arrimg[i,j,1] >= 225) and (arrimg[i,j,1] <=255) ):
                    arrimg[i,j,1] = 255
                else:
                    arrimg[i,j,1] = 0
                
                arrimg[i,j,2] = 0
        #newimage[:,:,1] = R
        #newimage[:,:,2] = G
        #newimage[:,:,3] = B
        #newimage=[R,G,B]
        #newimage1=np.array(newimage)
        new_im = Image.fromarray(arrimg)
        #newImg= MatrixToImage(newimage)
        filelistnew=filelist[num].strip('.jpg')
        new_im.save("test1/"+filelistnew+".png")

In [16]:
def ModifyRGBValue2(filelist):
    for num in range(len(filelist)):
        img=Image.open('test/'+filelist[num])
        #img=Image.open('test/1.jpg')
        arrimg = np.array(img)
        [x,y,z] = arrimg.shape
        R=arrimg[:,:,0]    #red
        G=arrimg[:,:,1]    #green
        B=arrimg[:,:,2];   #blue
        for i in range(x):
            for j in range(y):
                if( (arrimg[i,j,0] >= 235) and (arrimg[i,j,0] <=255) ):
                    arrimg[i,j,0] = 255
                elif( (arrimg[i,j,0] >= 133) and (arrimg[i,j,0] <=163) ):
                    arrimg[i,j,0] = 148
                else:
                    arrimg[i,j,0] = 0
                    
                if( (arrimg[i,j,1] >= 235) and (arrimg[i,j,1] <=255) ):
                    arrimg[i,j,1] = 255
                else:
                    arrimg[i,j,1] = 0
                    
                if( (arrimg[i,j,2] >= 235) and (arrimg[i,j,2] <=255) ):
                    arrimg[i,j,2] = 255
                elif( (arrimg[i,j,2] >= 191) and (arrimg[i,j,2] <=225) ):
                    arrimg[i,j,2] = 211
                else:
                    arrimg[i,j,2] = 0
        #newimage[:,:,1] = R
        #newimage[:,:,2] = G
        #newimage[:,:,3] = B
        #newimage=[R,G,B]
        #newimage1=np.array(newimage)
        new_im = Image.fromarray(arrimg)
        #newImg= MatrixToImage(newimage)
        filelistnew=filelist[num].strip('.jpg')
        new_im.save("test1/"+filelistnew+".png")

# 函数ModifyRGBValue3是可以使用的，功能能够实现

In [39]:
def ModifyRGBValue3(filelist):
    for num in range(len(filelist)):
        img=Image.open('ODandFovea/'+filelist[num])
        #img=Image.open('test/1.jpg')
        arrimg = np.array(img)
        [x,y,z] = arrimg.shape
        R=arrimg[:,:,0]    #red
        G=arrimg[:,:,1]    #green
        B=arrimg[:,:,2];   #blue
        val_RGB = 255
        if val_RGB in arrimg[:,:,0]:
            for i in range(x):
                for j in range(y):
                    if( (arrimg[i,j,0] >= 225) and (arrimg[i,j,0] <=255) ):
                        arrimg[i,j,0] = val_RGB
                    else:
                        arrimg[i,j,0] = 0
        else:
            for i in range(x):
                for j in range(y):
                    arrimg[i,j,0] = 0
            
        if val_RGB in arrimg[:,:,1]:
            for i in range(x):
                for j in range(y):
                    if( (arrimg[i,j,1] >= 225) and (arrimg[i,j,1] <=255) ):
                        arrimg[i,j,1] = val_RGB
                    else:
                        arrimg[i,j,1] = 0
        else:
            for i in range(x):
                for j in range(y):
                    arrimg[i,j,1] = 0
                    
        if val_RGB in arrimg[:,:,2]:
            for i in range(x):
                for j in range(y):
                    if( (arrimg[i,j,2] >= 225) and (arrimg[i,j,2] <=255) ):
                        arrimg[i,j,2] = val_RGB
                    else:
                        arrimg[i,j,2] = 0
        else:
            for i in range(x):
                for j in range(y):
                    arrimg[i,j,2] = 0
        #newimage[:,:,1] = R
        #newimage[:,:,2] = G
        #newimage[:,:,3] = B
        #newimage=[R,G,B]
        #newimage1=np.array(newimage)
        new_im = Image.fromarray(arrimg)
        #newImg= MatrixToImage(newimage)
        filelistnew=filelist[num].strip('.jpg')
        new_im.save("ODandFovea1/"+filelistnew+".png")

In [41]:
start = datetime.datetime.now()
ModifyRGBValue3(trainList1)
end = datetime.datetime.now()
print (end-start)

0:27:30.885891


In [29]:
#img=Image.open('test/'+filelist[i])
img=Image.open('test/1.jpg')
arrimg = np.array(img)
[x,y,z] = arrimg.shape
print([x,y,z])
new_im = Image.fromarray(arrimg)
print(new_im)
new_im.save("test1/1.jpg")

[5, 5, 3]
<PIL.Image.Image image mode=RGB size=5x5 at 0x1179F3080>


In [30]:
R=arrimg[:,:,0]    #red
G=arrimg[:,:,1]    #green
B=arrimg[:,:,2];   #blue
print(np.array(R)
#newimage=[R,G,B]
#newimage1=np.array(newimage)
#Image.fromarray(newimage1)
#new_im = Image.fromarray(newimage1)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [22]:
print(newimage1)

[[[ 10  10  10  10  10]
  [ 10  10  10  10  10]
  [ 10  10  10  10  10]
  [ 10  10  10  10  10]
  [ 10  10  10  10  10]]

 [[200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]]

 [[ 50  50  50  50  50]
  [ 50  50  50  50  50]
  [ 50  50  50  50  50]
  [ 50  50  50  50  50]
  [ 50  50  50  50  50]]]


In [15]:
print(arrimg[:,:,2])

[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]


In [16]:
[x,y,z] = arrimg.shape
print([x,y,z])

[5, 5, 3]


In [17]:
print(arrimg[:,:,0])

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [42]:
R=rgb(:,:,1); %red
G=rgb(:,:,2); %green
B=rgb(:,:,3); %blue
[x,y,z]=size(rgb);
for i=1:x
    for j=1:y
        if( (R(i,j) >= 225) && (R(i,j) <=255) )
            R(i,j) = 255;
        else
            R(i,j) = 0;
        end
        if( (G(i,j) >= 225) && (G(i,j) <=255) )
            G(i,j) = 255;
        else
            G(i,j) = 0;
        end
        B(i,j) = 0;
    end
end

% in this way
% blue(:,:,1)=R(:,:);
% blue(:,:,2)=G(:,:);
% blue(:,:,3)=B(:,:);

% another way
newimage(:,:,1) = R;
newimage(:,:,2) = G;
newimage(:,:,3) = B;


SyntaxError: invalid syntax (<ipython-input-42-03c2cb71509b>, line 1)